module.exports = {
    C: 'c',
    CPP: 'cpp',
    PYTHON: 'python',
    JAVA: 'java',
    NODEJS: 'nodejs',
    RUBY: 'ruby',
    PROMPTV1: 'promptv1',
    PROMPTV2: 'promptv2',
    JAVASCRIPT:'javascript',
    CSHARP:'c#',
    GO:'go',
    MULTIFILE: 'multifile',
    SQLITE3: 'sqlite3',
}
